on:
  push:
    branches:
      - release/*
  pull_request:
    branches:
      - master

name: macOS build
jobs:
  test-macOS:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.py }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macOS-latest, py: "3.9" }
    env:
      SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
    steps:
      - name: CHECKOUT CODE
        uses: actions/checkout@v2
      - name: SETUP PYTHON
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.py }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Cython
          pip install torch
          pip install -r requirements.txt
          pip install .
