on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Linux build
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #python-version: [ 3.7, 3.8, 3.9 ]
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install torch
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir Cython
          pip install --no-cache-dir torch
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install .
      - name: PKG-TEST
        run: |
          python -m unittest discover tests/
        env:
          HEREMAPS_API_KEY: ${{ secrets.HEREMAPS_API_KEY }}
          PLANET_API_KEY: ${{ secrets.PLANET_API_KEY }}
          EARTHENGINE_TOKEN: ${{ secrets.EARTHENGINE_TOKEN }}
      - name: Install from pypi
        run: |
          pip uninstall text2vec
          pip install -U text2vec
          python -c "import text2vec; print(text2vec.__version__)"
