on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Windows build
jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          python-version: 3.9
      - name: Install torch
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir torch
      - name: Test torch installation
        run: |
          python -c "import torch; print(torch.__version__)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir Cython
          pip install -r requirements.txt
          pip install .