on:
  push:
    branches:
      - release/*
  pull_request:
    branches:
      - master

name: Windows build
jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Windows')
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/checkout@v2
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          python-version: 3.9
      - name: Install torch
        run: |
          python -m pip install --upgrade pip
          pip install torch
      - name: Test torch installation
        run: |
          python -c "import torch; print(torch.__version__)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Cython
          pip install -r requirements.txt
          pip install .
      - name: Test from pypi
        run: |
          pip uninstall -y text2vec # install from pypi
          pip install -U text2vec
